{% set name = 'bob.bio.gmm' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.learn.linear
    - bob.sp
    - bob.learn.em
    - bob.measure
    - bob.db.base
    - bob.bio.base >3.1
    - matplotlib {{ matplotlib }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('matplotlib') }}


test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - bob.db.atnt
    - bob.io.image
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running biometric recognition experiments using GMM-based approximation
  license_family: BSD
