{% set name = 'bob.bio.gmm' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - verify_gmm.py    = bob.bio.gmm.script.verify_gmm:main
    - verify_isv.py        = bob.bio.gmm.script.verify_isv:main
    - verify_ivector.py = bob.bio.gmm.script.verify_ivector:main
    - train_gmm.py      = bob.bio.gmm.script.train_gmm:main
    - train_isv.py          = bob.bio.gmm.script.train_isv:main
    - train_ivector.py   = bob.bio.gmm.script.train_ivector:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.learn.activation
    - bob.math
    - bob.learn.linear
    - bob.sp
    - bob.learn.em
    - bob.measure
    - bob.db.base
    - bob.bio.base >3.1
    - matplotlib {{ matplotlib }}
  run:
    - python
    - setuptools
    - bob.bio.base >3.1
    - matplotlib

test:
  imports:
    - {{ name }}
  commands:
    - verify_gmm.py --help
    - verify_isv.py --help
    - verify_ivector.py --help
    - train_gmm.py --help
    - train_isv.py --help
    - train_ivector.py --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running biometric recognition experiments using GMM-based approximation
  license_family: BSD
